.TH roctran 1
.SH NAME
roctran \- A lightweight LAN file transfer tool.
.SH SYNOPSIS
.B rocreceive
[\-option...]
.B rocsend
[\-option...]
.SH DESCRIPTION
.PP
\fIrocreceive\fP a file transfer server.
\fIrocsend\fP a file transfer client.
.SH OPTIONS
.SH SEE ALSO
.SH COPYRIGHT
.SH BUGS
.SH AUTHORS
rocrocket@2010
